service: stocks-serverless

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-south-1:429937773353:table/stocksTable"

functions:

  get:
    handler: get.list
    events:
      - http:
          path: stocks/
          method: get
          cors: true
        
  # update:
  #   handler: todos/update.update
  #   events:
  #     - http:
  #         path: todos/{id}
  #         method: put
  #         cors: true
  
  delete:
    handler: delete.delete
    events:
      - http:
          path: stocks/{id}
          method: delete
          cors: true

  post:
    handler: create.create
    events:
      - http:
          path: stocks/
          method: post
          cors: true
